export enum AuthErrorCode {
    TOKEN_EXPIRED = "TOKEN_EXPIRED",
    TOKEN_INVALID = "TOKEN_INVALID",
    TOKEN_MISSING = "TOKEN_MISSING",
    UNAUTHORIZED = "UNAUTHORIZED",
    EMAIL_EXISTS = "EMAIL_EXISTS",
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
    USER_NOT_FOUND = "USER_NOT_FOUND",
    RESET_TOKEN_USED = "RESET_TOKEN_USED",
    SAME_PASSWORD = "SAME_PASSWORD",
}